services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=notice_tracker'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'